### Introduction To Pandas Module
Here, we are learning data analysis. Pandas is a software library written for the Python programming language that helps with data manipulation and analysis. It offers various data structures which help in the manipulation of data. <br>
One of the data structures used is DataFrame.<br>
DataFrame is used as a way to store data in a rectangular grid.<br>
Similar to how data is stored in Microsoft Excel.
### Installation
We can easily install this library using the terminal. Follow the steps given below to install Pandas:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install pandas with the help of pip easily. Head over to the directory where you want to install the pandas and fire the below command:<br>
__pip install pandas__<br>
This is very simple to install.

In [1]:
# !pip install pandas

### Other way to install
If the above steps do not work for you, here is another way to install:<br>
Step 1: Go to your browser. Search for __python unofficial binaries__, or click <br>
https://www.lfd.uci.edu/~gohlke/pythonlibs/<br> 
and you will be redirected to the binary page.<br>
Step 2: To download the library, search for pandas – Ctrl + F will help you. Download pandas library based on your python version. <br>
Step 3: After the installation, head over to the directory where you've downloaded the pandas. <br>
Step 4: Right-click to open Windows PowerShell. Pip can help us with the installation. Just go to that location in your terminal and run the following command: <br>
__pip install pandas__ <br>
Complete this command by the TAB button so that the location of your folder is mentioned.

### import pandas
Once Pandas is installed, import it in your applications by adding the import keyword:<br>
__import pandas as pd__<br>
Now Pandas is imported and ready to use.

In [169]:
import pandas

In [170]:
students = {
    'Name': ["Muhammad Ayub ", " Ibraheem khan", "Muhammad Abid", "Shumail Khan","Qasim Ali"],
    'Marks': [80, 72, 77, 65, 15],
    'Class':["1st Year", "2nd Year", "1st Year", "3rd Year", "2nd Year"],
    'Age': [20, 21, 19, 22, 21]
}

In [171]:
df = pandas.DataFrame(students)

In [172]:
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

### Pandas as pd
Pandas is usually imported under the pd alias.
#### alias: 
In Python alias are an alternate name for referring to the same thing.<br>
Create an alias with the as keyword while importing:<br>
__import pandas as pd__<br>
Now the Pandas package can be referred to as pd instead of pandas.

In [86]:
import pandas as pd

In [87]:
df = pd.DataFrame(students)

In [88]:
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

### Checking Pandas Version
The version string is stored under __version__ attribute.

In [89]:
pd.__version__

'2.1.4'

## Saving to CSV and other extensions like excel

In [173]:
df.to_csv('pythonMonday.csv')

## Remove Index and saving the csv file

In [174]:
df.to_csv('pythonMondayRemoveIndex.csv', index=False)

## Show some rows from the Start

In [92]:
df

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [93]:
df.head()

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

## Specify No of rows to show

In [94]:
df.head(3)

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19

In [14]:
df.tail(3)

            Name  Marks     Class  Age
2  Muhammad Abid     77  1st Year   19
3   Shumail Khan     65  3rd Year   22
4      Qasim Ali     15  2nd Year   21

In [95]:
df.tail()

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [96]:
df.describe()

           Marks        Age
count   5.000000   5.000000
mean   61.800000  20.600000
std    26.771253   1.140175
min    15.000000  19.000000
25%    65.000000  20.000000
50%    72.000000  21.000000
75%    77.000000  21.000000
max    80.000000  22.000000

# Reading csv or other files

In [175]:
classData= pd.read_csv("pythonMondayRemoveIndex.csv")
classData

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   20
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [176]:
classData= pd.read_csv("pythonMonday.csv")
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [177]:
classData.drop('Name', axis=1)

   Unnamed: 0  Marks     Class  Age
0           0     80  1st Year   20
1           1     72  2nd Year   21
2           2     77  1st Year   19
3           3     65  3rd Year   22
4           4     15  2nd Year   21

In [178]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [179]:
classData.drop(1, axis=0)

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [102]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   20
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

# Check the spelling

In [23]:
classData['class']

KeyError: 'class'

# Check the trail space

In [104]:
classData['Class ']

KeyError: 'Class '

# Corrected Spelling

In [180]:
classData['Name']

0    Muhammad Ayub
1     Ibraheem khan
2     Muhammad Abid
3      Shumail Khan
4         Qasim Ali
Name: Name, dtype: object

# Check the head space

In [106]:
classData[' Name']

KeyError: ' Name'

In [108]:
type(classData)

pandas.core.frame.DataFrame

In [107]:
type(classData['Name'])

pandas.core.series.Series

In [181]:
classData['Age']

0    20
1    21
2    19
3    22
4    21
Name: Age, dtype: int64

classData['gpa'][0]

In [110]:
classData['Age'][0]

20

In [182]:
classData['Age'][0]=90

C:\Users\PMYLS\AppData\Local\Temp\ipykernel_7800\883805414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  classData['Age'][0]=90

In [183]:
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   90
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

In [113]:
classData['Age'][4]

21

In [114]:
classData['Age'][4]=5

C:\Users\PMYLS\AppData\Local\Temp\ipykernel_7800\1411840039.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  classData['Age'][4]=5

In [ ]:
classData["Name"][4]

# Rename the column name

In [115]:
classData.rename(columns={'Age': 'AGE'})

   Unnamed: 0            Name  Marks     Class  AGE
0           0  Muhammad Ayub      80  1st Year   90
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year    5

## Create Labels
With the index argument, you can name your own labels.

In [116]:
classData.index = ["First","Second", "Third", "Fourth", "Fifth"]
classData

        Unnamed: 0            Name  Marks     Class  Age
First            0  Muhammad Ayub      80  1st Year   90
Second           1   Ibraheem khan     72  2nd Year   21
Third            2   Muhammad Abid     77  1st Year   19
Fourth           3    Shumail Khan     65  3rd Year   22
Fifth            4       Qasim Ali     15  2nd Year    5

# Asignment

In [185]:
classData.drop('Unnamed: 0', axis=1)

             Name  Marks     Class  Age
0  Muhammad Ayub      80  1st Year   90
1   Ibraheem khan     72  2nd Year   21
2   Muhammad Abid     77  1st Year   19
3    Shumail Khan     65  3rd Year   22
4       Qasim Ali     15  2nd Year   21

In [186]:
classdata = classData.drop('Unnamed: 0', axis=1)
classData

   Unnamed: 0            Name  Marks     Class  Age
0           0  Muhammad Ayub      80  1st Year   90
1           1   Ibraheem khan     72  2nd Year   21
2           2   Muhammad Abid     77  1st Year   19
3           3    Shumail Khan     65  3rd Year   22
4           4       Qasim Ali     15  2nd Year   21

# Inplace

In [117]:
classData.drop('Unnamed: 0', axis=1, inplace = True)
classData

                  Name  Marks     Class  Age
First   Muhammad Ayub      80  1st Year   90
Second   Ibraheem khan     72  2nd Year   21
Third    Muhammad Abid     77  1st Year   19
Fourth    Shumail Khan     65  3rd Year   22
Fifth        Qasim Ali     15  2nd Year    5

In [118]:
classData

                  Name  Marks     Class  Age
First   Muhammad Ayub      80  1st Year   90
Second   Ibraheem khan     72  2nd Year   21
Third    Muhammad Abid     77  1st Year   19
Fourth    Shumail Khan     65  3rd Year   22
Fifth        Qasim Ali     15  2nd Year    5

# Accessing the value in Dataframe

In [26]:
classData["Name"]

0    Muhammad Ayub
1     Ibraheem khan
2     Muhammad Abid
3      Shumail Khan
4         Qasim Ali
Name: Name, dtype: object

In [27]:
classData["Name"]["Fifth"]

KeyError: 'Fifth'

## Pandas 
Pandas is an open source data analysis library written in Python.<br>
It uses the power and speed of numpy to make data analysis and preprocessing easy for data scientists.<br>
__Pandas__ is used to analyze data.<br>
Python data analysis using pandas is a great start to Exploratory Data Analysis (EDA) for a data scientist.

## Pandas Data Structure
Panda has two types of Data Structure:<br> 
    a) Series<br>
    b) Dataframe
### Series
It is a one dimentional array with indexes. It stores a single column or row of data in a Dataframe.<br>
It is a one dimensional array capable of holding any type of data.
### Dataframe
It is a tabular spreadsheet like structure representing rows each of which contains one or more columns.<br>
It is a multi dimensional array capable of holding any type of data.<br>
__Series__ is like a column, a __DataFrame__ is the whole table.

In [ ]:
classData['Age']

In [ ]:
 type(classData['Age'])

In [ ]:
classData

In [ ]:
type(classData)

In [119]:
import numpy as np

In [120]:
series1= pd.Series(np.random.rand())

In [121]:
series1

0    0.868069
dtype: float64

In [122]:
series1= pd.Series(np.random.rand(30))

In [123]:
series1

0     0.657794
1     0.616216
2     0.874429
3     0.018684
4     0.768349
5     0.031785
6     0.732648
7     0.468565
8     0.566553
9     0.394947
10    0.339090
11    0.613644
12    0.309872
13    0.253234
14    0.292602
15    0.315246
16    0.678459
17    0.331180
18    0.420041
19    0.240173
20    0.182486
21    0.261971
22    0.889009
23    0.014944
24    0.395098
25    0.581953
26    0.597675
27    0.665255
28    0.156490
29    0.092513
dtype: float64

In [124]:
type(series1)

pandas.core.series.Series

In [125]:
np.random.rand(3,4)

array([[9.47156456e-01, 6.06351093e-02, 9.00726589e-01, 4.46735761e-01],
       [1.03220692e-01, 2.75932301e-01, 9.97966781e-01, 9.31072003e-04],
       [6.25862028e-01, 5.05920087e-01, 3.49527452e-01, 7.56105193e-01]])

In [128]:
newDf = pd.DataFrame(np.random.rand(330,5))
# newDf = pd.DataFrame(np.random.rand(330,5), index=np.arange(330))

In [129]:
type(newDf)

pandas.core.frame.DataFrame

In [130]:
newDf.head(2)

          0         1         2         3         4
0  0.071659  0.053539  0.577694  0.149656  0.250617
1  0.829765  0.702537  0.170021  0.767394  0.409780

In [131]:
newDf.tail(2)

            0         1         2         3         4
328  0.159392  0.192224  0.256405  0.834375  0.961702
329  0.267107  0.184517  0.279769  0.262973  0.145641

In [132]:
newDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       330 non-null    float64
 1   1       330 non-null    float64
 2   2       330 non-null    float64
 3   3       330 non-null    float64
 4   4       330 non-null    float64
dtypes: float64(5)
memory usage: 13.0 KB

In [133]:
newDf.describe()

                0           1           2           3           4
count  330.000000  330.000000  330.000000  330.000000  330.000000
mean     0.497238    0.478598    0.533862    0.517721    0.511718
std      0.300523    0.282894    0.286243    0.291697    0.299361
min      0.002541    0.000548    0.000812    0.000036    0.000168
25%      0.220138    0.244081    0.314676    0.300652    0.243268
50%      0.498916    0.456495    0.529615    0.501387    0.529532
75%      0.770012    0.705883    0.772190    0.773505    0.777838
max      0.999672    0.998975    0.999895    0.998422    0.996240

In [134]:
newDf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

# Change the value inside the dataframe

In [135]:
newDf[0][0]= 10000.0

In [136]:
newDf

                0         1         2         3         4
0    10000.000000  0.053539  0.577694  0.149656  0.250617
1        0.829765  0.702537  0.170021  0.767394  0.409780
2        0.752383  0.057536  0.939825  0.958262  0.237424
3        0.358952  0.523981  0.966682  0.425873  0.990508
4        0.247553  0.554370  0.674384  0.638962  0.738900
..            ...       ...       ...       ...       ...
325      0.962042  0.799871  0.714804  0.842758  0.856560
326      0.927275  0.061766  0.361509  0.482754  0.310909
327      0.415293  0.587988  0.860444  0.753959  0.186442
328      0.159392  0.192224  0.256405  0.834375  0.961702
329      0.267107  0.184517  0.279769  0.262973  0.145641

[330 rows x 5 columns]

In [137]:
newDf.head()

              0         1         2         3         4
0  10000.000000  0.053539  0.577694  0.149656  0.250617
1      0.829765  0.702537  0.170021  0.767394  0.409780
2      0.752383  0.057536  0.939825  0.958262  0.237424
3      0.358952  0.523981  0.966682  0.425873  0.990508
4      0.247553  0.554370  0.674384  0.638962  0.738900

# Transpose

In [138]:
newDf.T

,0,1,2,3,4,5,6,7,8,9,...,320,321,322,323,324,325,326,327,328,329
0,10000.000000,0.829765,0.752383,0.358952,0.247553,0.902797,0.821940,0.971893,0.241234,0.873172,...,0.340022,0.913982,0.270708,0.723429,0.297802,0.962042,0.927275,0.415293,0.159392,0.267107
1,0.053539,0.702537,0.057536,0.523981,0.554370,0.663549,0.205853,0.800891,0.845378,0.131997,...,0.237146,0.566765,0.347083,0.521803,0.185349,0.799871,0.061766,0.587988,0.192224,0.184517
2,0.577694,0.170021,0.939825,0.966682,0.674384,0.761876,0.267703,0.873100,0.666042,0.034248,...,0.305584,0.559220,0.274160,0.039384,0.137565,0.714804,0.361509,0.860444,0.256405,0.279769
3,0.149656,0.767394,0.958262,0.425873,0.638962,0.898890,0.666840,0.986548,0.374778,0.298191,...,0.611215,0.700240,0.547524,0.388891,0.998422,0.842758,0.482754,0.753959,0.834375,0.262973
4,0.250617,0.409780,0.237424,0.990508,0.738900,0.860906,0.208216,0.254014,0.166844,0.033347,...,0.297488,0.041851,0.957761,0.838564,0.679813,0.856560,0.310909,0.186442,0.961702,0.145641

# Sorting

In [139]:
newDf.sort_index(axis=0)

                0         1         2         3         4
0    10000.000000  0.053539  0.577694  0.149656  0.250617
1        0.829765  0.702537  0.170021  0.767394  0.409780
2        0.752383  0.057536  0.939825  0.958262  0.237424
3        0.358952  0.523981  0.966682  0.425873  0.990508
4        0.247553  0.554370  0.674384  0.638962  0.738900
..            ...       ...       ...       ...       ...
325      0.962042  0.799871  0.714804  0.842758  0.856560
326      0.927275  0.061766  0.361509  0.482754  0.310909
327      0.415293  0.587988  0.860444  0.753959  0.186442
328      0.159392  0.192224  0.256405  0.834375  0.961702
329      0.267107  0.184517  0.279769  0.262973  0.145641

[330 rows x 5 columns]

In [140]:
newDf.sort_index(axis=0, ascending=False)

                0         1         2         3         4
329      0.267107  0.184517  0.279769  0.262973  0.145641
328      0.159392  0.192224  0.256405  0.834375  0.961702
327      0.415293  0.587988  0.860444  0.753959  0.186442
326      0.927275  0.061766  0.361509  0.482754  0.310909
325      0.962042  0.799871  0.714804  0.842758  0.856560
..            ...       ...       ...       ...       ...
4        0.247553  0.554370  0.674384  0.638962  0.738900
3        0.358952  0.523981  0.966682  0.425873  0.990508
2        0.752383  0.057536  0.939825  0.958262  0.237424
1        0.829765  0.702537  0.170021  0.767394  0.409780
0    10000.000000  0.053539  0.577694  0.149656  0.250617

[330 rows x 5 columns]

In [141]:
newDf.sort_index(axis=1)

                0         1         2         3         4
0    10000.000000  0.053539  0.577694  0.149656  0.250617
1        0.829765  0.702537  0.170021  0.767394  0.409780
2        0.752383  0.057536  0.939825  0.958262  0.237424
3        0.358952  0.523981  0.966682  0.425873  0.990508
4        0.247553  0.554370  0.674384  0.638962  0.738900
..            ...       ...       ...       ...       ...
325      0.962042  0.799871  0.714804  0.842758  0.856560
326      0.927275  0.061766  0.361509  0.482754  0.310909
327      0.415293  0.587988  0.860444  0.753959  0.186442
328      0.159392  0.192224  0.256405  0.834375  0.961702
329      0.267107  0.184517  0.279769  0.262973  0.145641

[330 rows x 5 columns]

In [40]:
newDf.sort_index(axis=1, ascending=False)

NameError: name 'newDf' is not defined

In [ ]:
newDf.head()

In [41]:
newDf[0][1]

NameError: name 'newDf' is not defined

In [ ]:
type(newDf[0])

In [42]:
newDf

NameError: name 'newDf' is not defined

## view

In [43]:
newDfView=newDf

NameError: name 'newDf' is not defined

In [ ]:
newDfView

In [44]:
newDfView[0][0]=765

NameError: name 'newDfView' is not defined

In [ ]:
newDf.head()

In [45]:
newDfView.head()

NameError: name 'newDfView' is not defined

In [ ]:
newDfCopy=newDf.copy()

In [46]:
newDfCopy[0][0]=656

NameError: name 'newDfCopy' is not defined

In [47]:
newDf.head()

NameError: name 'newDf' is not defined

In [ ]:
newDfCopy.head()

In [142]:
import pandas as pd

# Create a sample DataFrame
data = {
    "Student": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
   Student  Marks  Age
0     Ali     85   20
1    Sara     92   21
2   Bilal     76   19
3    Hina     89   22

In [49]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  4 non-null      object
 1   Marks    4 non-null      int64
 2   Age      4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes
None

In [50]:
print("\nDescribe:\n", df.describe())

Describe:
            Marks        Age
count   4.000000   4.000000
mean   85.500000  20.500000
std     6.952218   1.290994
min    76.000000  19.000000
25%    82.750000  19.750000
50%    87.000000  20.500000
75%    89.750000  21.250000
max    92.000000  22.000000

In [51]:
# -----------------------------
# 2. SORTING
# -----------------------------
print("\nSorting by Marks (descending):\n", df.sort_values("Marks", ascending=False))
print("\nSorting by Age (ascending):\n", df.sort_values("Age"))

Sorting by Marks (descending):
   Student  Marks  Age
1    Sara     92   21
3    Hina     89   22
0     Ali     85   20
2   Bilal     76   19

Sorting by Age (ascending):
   Student  Marks  Age
2   Bilal     76   19
0     Ali     85   20
1    Sara     92   21
3    Hina     89   22

In [52]:
# -----------------------------
# 3. TRANSPOSE
# -----------------------------
print("\nTransposed DataFrame:\n", df.T)

Transposed DataFrame:
            0     1      2     3
Student  Ali  Sara  Bilal  Hina
Marks     85    92     76    89
Age       20    21     19    22

## Slicing through loc function

In [144]:
import pandas as pd

# Sample DataFrame
data = {
    "Name": ["Ali", "Sara", "Bilal", "Hina"],
    "Marks": [85, 92, 76, 89],
    "Age": [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
     Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [145]:
# 1. Select row with label 2
print(df.loc[2])

Name     Bilal
Marks       76
Age         19
Name: 2, dtype: object

In [146]:
# 2. Select specific rows and columns by NAME
print(df.loc[1:2, ["Name", "Marks"]])

    Name  Marks
1   Sara     92
2  Bilal     76

In [188]:
df["Marks"] > 85

0    False
1    False
2    False
3    False
4    False
Name: Marks, dtype: bool

In [56]:

# 3. Applying Filter: Conditional selection: students with Marks > 85
print(df.loc[df["Marks"] > 85])

   Name  Marks  Age
1  Sara     92   21
3  Hina     89   22

##  Slicing through iloc

In [57]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [58]:
# 1. Select row at index 0
print(df.iloc[0])

Name     Ali
Marks     85
Age       20
Name: 0, dtype: object

In [59]:
# 2. Select 2 rows and 2 columns by position
print(df.iloc[0:2, 0:2])

   Name  Marks
0   Ali     85
1  Sara     92

In [60]:
# 3. Select last row using negative index
print(df.iloc[-1])

Name     Hina
Marks      89
Age        22
Name: 3, dtype: object

# Dropping the Row

In [61]:
df

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [62]:
df.drop(0).head()

    Name  Marks  Age
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

# Dropping the col

In [63]:
df.drop(['Age'], axis=1).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [64]:
df.head()

    Name  Marks  Age
0    Ali     85   20
1   Sara     92   21
2  Bilal     76   19
3   Hina     89   22

In [65]:
df.drop(['Age'], axis=1, inplace=True)

In [66]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [67]:
df.reset_index().head()

   index   Name  Marks
0      0    Ali     85
1      1   Sara     92
2      2  Bilal     76
3      3   Hina     89

In [68]:
df.reset_index(drop=True).head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [69]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

In [70]:
df.reset_index(drop=True, inplace=True)

In [71]:
df.head()

    Name  Marks
0    Ali     85
1   Sara     92
2  Bilal     76
3   Hina     89

# Groupby
The groupby method allows you to group rows of data together and call aggregate functions

​
​

In [189]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [190]:
df = pd.DataFrame(data)

In [191]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

### Now you can use the .groupby() method to group rows together based off of a column name.
For instance let's group based off of Company. This will create a DataFrameGroupBy object:

In [158]:
df.groupby('Company')

##### You can save this object as a new variable:

In [162]:
by_comp = df.groupby("Company")
type(by_comp)

pandas.core.groupby.generic.DataFrameGroupBy

#### And then call aggregate methods of the object:

In [192]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [194]:
df.groupby('Company')['Sales'].agg(['mean'])

          mean
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [154]:
df.groupby('Company').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [161]:
by_comp.std()

ValueError: could not convert string to float: 'Sam'

In [ ]:
by_comp.min()

In [ ]:
by_comp.max()

In [ ]:
by_comp.count()

In [ ]:
by_comp.describe()